language: go
sudo: false
go:
  - 1.5.3
  - 1.6
  - tip
env:
  global:
    - GOARCH=amd64
    - GO15VENDOREXPERIMENT=1
script:
  - make test
notifications:
  email:
    on_success: change
    on_failure: always
matrix:
  allow_failures:
    - go: tip
